### ISSUE TITLE
Initialize Backend folder

### ISSUE THREAD

**Issue by abedmohammed** [DSC-McMaster-U/ai-journal#2]

**Comment by aidenchenderson** [comment]
Looking into the backend of AutoML, it seems like we could get started on discussing what frameworks, languages, etc. the group would like to use. Anyone have anything in particular they think would work well? Other than that, we could start initializing files that we will need, like README or any subfolders, to keep our code modular and clean.

**Comment by abedmohammed** [comment]
Okay so funny enough there are more reasons to go away from NextJS backend (nextjs can be used as a fullstack application and you can create API routes with it) https://www.youtube.com/watch?v=6xvLUWpCSFM (basically says nextjs is bad for websockets which we want to use when working with the journals)

So we should definitely go with something like expressjs

**Comment by AustinBray77** [comment]
Currently the backend has been initialized on the backend branch as a JavaScript Express server, was just wondering if we should make it TypeScript or not?
