### ISSUE TITLE
[TASK-5] Choose and setup Dev Database

### ISSUE THREAD

**Issue by abedmohammed** [DSC-McMaster-U/ai-journal#3]

**Comment by ausbennett** [comment]
I don't have experience with supabase, however I do like the idea of going that route or postgres and avoiding firebase. If the point of this team is to learn new things idk how difficult it is to do plain postgres out right and build on it ourselves so we can build everything from the ground up

**Comment by BaoGeist** [comment]
I'd be interested in building it from the ground up as well. I was looking into a mySQL instance but postgres would be fine as well. Was there any particular reason for postgres?
