### ISSUE TITLE
[TASK-17] Implement Journal Tabs Component on Journals Page

### ISSUE THREAD

**Issue by abedmohammed** [DSC-McMaster-U/ai-journal#37]
## [TASK-17] Implement Journal Tabs Component on Journals Page

**Goal:**  
Develop a tabs component on the Journals page that allows users to switch between different journal views, manage tabs, and navigate to specific journal entries.

**Requirements:**

1. **Main Journal Tab:**
   - Create a default main journal tab that displays the user's primary journal entries.
   - Ensure this tab is selected by default upon opening the Journals page.

2. **Hamburger Menu for Tab View:**
   - Add a hamburger icon that opens a tab view sidebar or modal, displaying a list of all journal tabs.
   - The sidebar or modal should close upon selecting a tab or tapping outside the view.

3. **Tab Selection and Journal View Switching:**
   - Enable users to select tabs from the tab view to open different journal views.
   - Ensure that selecting a tab dynamically loads the corresponding journal entries for that tab.

4. **Navigation Routing:**
   - Set up routes for different journal views:
     - `/journals/daily` for the main daily journal.
     - `/journals/:tab/:journalId` for specific tab views.
   - Ensure smooth navigation between these routes based on the selected tab.

5. **Tab Management:**
   - Provide options for creating, deleting, and editing tabs:
     - "Create Tab" to add a new journal tab.
     - "Delete Tab" to remove an existing tab.
     - "Edit Tab Name" to rename a tab.
   - Display prompts or confirmations for actions like deleting a tab to prevent accidental deletions.

**Comment by LucasAMachado** [comment]
Completed Task.
